name: Ubuntu 16.04 / Qt 5.15
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  buildUbuntuXenial:
    runs-on: ubuntu-16.04
    env:
      CC: gcc-9
      CXX: g++-9

    steps:
    - name: get container ready for build
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -q --force-yes \
        automake cmake git wget libfuse2 desktop-file-utils tree \
        build-essential libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev

        # Packaging requirements
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -q --force-yes \
        libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 \
        libxcb-xinerama0 libxcb-composite0 libxcb-cursor0 libxcb-damage0 \
        libxcb-dpms0 libxcb-dri2-0 libxcb-dri3-0 libxcb-ewmh2 libxcb-glx0 \
        libxcb-present0 libxcb-randr0 libxcb-record0 libxcb-render0 libxcb-res0 \
        libxcb-screensaver0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1

    - name: install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        modules: 'qtcharts qtsvg'
        install-deps: false

    - name: checkout sources
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: build Ripes
      run: |
        echo "--------------------------------------------------------------"
        echo "building desktop"
        # now build for the desktop version
        cmake -DCMAKE_BUILD_TYPE=Release .
        make -j $(nproc)

    - name: package artifacts
      run: |
        mkdir -p appdir/usr/bin/
        mv Ripes appdir/usr/bin/        
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        source .github/scripts/set_version.sh
        export VERSION=${RIPES_VERSION}-linux # linuxdeployqt uses this for naming the package
        echo "Version is: ${VERSION}"
        ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract-and-run appdir/usr/share/applications/*.desktop \
          -appimage -verbose=2 -extra-plugins=iconengines

    - name: continuous release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/master'
      with:
        prerelease: true
        name: Continuous
        files: Ripes*.AppImage*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: tagged release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Ripes*.AppImage*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
