name: Mac
on:
  push:
    branches:
    - master

jobs:
  buildMac:
    runs-on: macOS-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: setup Homebrew
      run: brew install autoconf automake libtool xz  pkg-config libgit2 libjpg libpng libmtp

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        modules: 'qtcharts qtsvg'
        install-deps: false

    - name: build Ripes 
      run: |
        export QT_ROOT=${GITHUB_WORKSPACE}/Qt/5.13.0/clang_64
        export QT_QPA_PLATFORM_PLUGIN_PATH=$QT_ROOT/plugins
        export PATH=$QT_ROOT/bin:$PATH
        export CMAKE_PREFIX_PATH=$QT_ROOT/lib/cmake
        DIR=$(pwd)
        cmake -DCMAKE_BUILD_TYPE=Release .
        make
