name: Mac
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  buildMac:
    runs-on: macOS-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: setup Homebrew
      run: brew install autoconf automake libtool xz  pkg-config libgit2 libjpg libpng libmtp
    - name: set our Qt build
      run: |
        mkdir -p Qt/5.13.0
        curl --output Qt-5.13.0-mac.tar.xz https://f002.backblazeb2.com/file/Subsurface-Travis/Qt-5.13.0-mac.tar.xz
        tar -xJ -C Qt/5.13.0 -f Qt-5.13.0-mac.tar.xz

    - name: build Ripes
      run: |
        export QT_ROOT=${GITHUB_WORKSPACE}/Qt/5.13.0/clang_64
        export QT_QPA_PLATFORM_PLUGIN_PATH=$QT_ROOT/plugins
        export PATH=$QT_ROOT/bin:$PATH
        export CMAKE_PREFIX_PATH=$QT_ROOT/lib/cmake
        DIR=$(pwd)
        cmake -DCMAKE_BUILD_TYPE=Release .
        make
